### ISSUE TITLE
How to work with corejs option for babel preset-env?

### ISSUE THREAD

**Issue by theimowski** [fable-compiler/webpack-config-template#12]
https://github.com/fable-compiler/webpack-config-template/commit/8580b50360468925686ea26e2ad70dd18b457d97 adds "corejs" option to "preset-env" but when using that I get following error from webpack:

```
ERROR in ./src/Client/Client.fsproj
Module build failed (from ./node_modules/fable-loader/index.js):
Error: [BABEL] unknown: Invalid Option: corejs is not a valid top-level option.
        Maybe you meant to use 'targets'? (While processing: "/Users/theimowski/sandbox/safe-template/254/node_modules/@babel/preset-env/lib/index.js")
```

What is necessary to get it working?

**Comment by alfonsogarciacaro** [comment]
Ah, I didn't know that option wasn't backwards compatible. I guess you have to update `babel-core` in your package.json (and/or `babel-loader`).

**Comment by theimowski** [comment]
Thanks that helped - upgraded all following packages: 
```
yarn upgrade @babel/core @babel/plugin-transform-runtime @babel/polyfill @babel/preset-env @babel/runtime babel-loader
```

I also had to add `core-js` package as it was missing.
