### ISSUE TITLE
SASS/SCSS url guidance

### ISSUE THREAD

**Issue by aolney** [fable-compiler/webpack-config-template#14]
I have a url in my sass file, e.g.
```
.loading
  background-image: url('/img/loading.gif')
```
This works fine with the current webpack-config. Note the first slash. The sass file lives in src.

However, when I deploy to GitHub Pages, the first slash is now a problem. What I want then is 'img/loading.gif' without the first slash.

This seems to be a [well known issue with `url`, sass-loader, and webpack](https://webpack.js.org/loaders/sass-loader/#problems-with-url).

Any shared wisdom would be appreciated. It may be that adding `resolve-url-loader` to the template would be a good idea.

**Comment by MangelMaxime** [comment]
This template excepts you to put your assets in a `public` next to your `src` folder.

[Source](https://github.com/fable-compiler/webpack-config-template/blob/master/webpack.config.js#L22

- In dev mode, we serve the `public` content [source](https://github.com/fable-compiler/webpack-config-template/blob/master/webpack.config.js#L102)
- In production mode, we copy the `public` content in the output dear next to your `*.js` file [source](https://github.com/fable-compiler/webpack-config-template/blob/master/webpack.config.js#L90)

**Comment by aolney** [comment]
My setup/version of the template matches these specifications.

All the example solutions I'm finding for this problem, e.g. [this one](https://stackoverflow.com/questions/52219401/webpack-style-loader-css-loader-url-path-resolution-not-working) are using `resolve-url-loader`.

**Comment by MangelMaxime** [comment]
In theory, if your `img` folder is right under `public` you don't need to use `/` in the URL. 

But I can be wrong, if this doesn't work feel free to send a PR to include `resolve-url-loader` :)

**Comment by aolney** [comment]
Right, I don't need /img/file.gif for the deployment, but when I run webpack-dev-server during development it needs the absolute path with the leading slash.

Is there a way to fix that, and so avoid the issue?

**Comment by MangelMaxime** [comment]
I don't know I didn't experience this issue myself but it's probably because I didn't include asset via `sass` or it was coming from `FontAwesome` which ask for a path variable in scss
