### ISSUE TITLE
Problem with copy-webpack-plugin: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by 0101** [fable-compiler/webpack-config-template#17]
When trying to build for production I was getting:
```log
    ERROR in Cannot read property 'map' of undefined
    Child HtmlWebpackCompiler:
         1 asset
        Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
        [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html 2.28 KiB {0} [built]
```

Took me a while to track it down, but the cause was that CopyWebpackPlugin options are supposed to be an object, not a list. (At least in the latest version 6.0.2)

So changing:
```js
new CopyWebpackPlugin([{
    patterns: [{
        from: resolve(CONFIG.assetsDir) }]
    }])
```

To:
```js
new CopyWebpackPlugin({
    patterns: [{
        from: resolve(CONFIG.assetsDir) }]
    })
```

Fixed the problem for me.

**Comment by alfonsogarciacaro** [comment]
Oh, sorry. Wrong copy and paste here, thanks a lot for the fix!

**Comment by nikolaz111** [comment]
Can you change the docs to avoid having this issue?

**Comment by MangelMaxime** [comment]
@nikolaz111 Can you please link us the documentation which still has the typo ?
