### ISSUE TITLE
Don't we need NamedModulesPlugin for HMR as well?

### ISSUE THREAD

**Issue by theimowski** [fable-compiler/webpack-config-template#5]
According to https://elmish.github.io/hmr/ one needs both:

```
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NamedModulesPlugin()
```

but the template doesn't contain `NamedModulesPlugin`

**Comment by alfonsogarciacaro** [comment]
The plugin is added automatically by Webpack in development mode :) https://webpack.js.org/concepts/mode/

**Comment by theimowski** [comment]
Thanks @alfonsogarciacaro I'll move escalate this to HMR repository then to correct the docs
