### ISSUE TITLE
Inconsistent use of double and single quotes in webpack.config.js

### ISSUE THREAD

**Issue by kqr** [fable-compiler/webpack-config-template#9]
My eslint complained about strings using double quotes instead of single quotes, but only for some of the strings. I don't care much which type of quote strings to use, but at least they should all use the same type of quote.

Or am I missing some sort of rule for when which type of quote is used?

**Comment by alfonsogarciacaro** [comment]
No mysterious rules :) It's probably due to the multiple patches applied to the file. It'd be a good idea to uniform the quote style, could you please send a PR for that? Thanks a lot in advance!

**Comment by MangelMaxime** [comment]
Closed by #10
